# Generated by Django 5.2.1 on 2025-05-26 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_availableproduct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="availableproduct",
            old_name="quantity_in_grams",
            new_name="quantity_in_ml",
        ),
    ]
